dist: trusty
sudo: false
language: cpp
services: docker
env: IMG=joecorcoran/cache-test
before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull $IMG:latest
script:
  - docker build --cache-from $IMG:latest --tag $IMG:$TRAVIS_COMMIT --tag $IMG:latest .
  - docker run --rm -it $IMG:$TRAVIS_COMMIT curl -i https://google.com
after_success:
  - docker push $IMG:latest
