dist: trusty
sudo: false
language: cpp
services: docker
env:
  - FOO=one
  - FOO=two
before_script:
  - docker pull joecorcoran/cache-test:latest
script:
  - docker build -t $FOO --cache-from joecorcoran/cache-test:latest .
  - docker run -it $FOO curl
  - echo "Done"
